Project 7: Mobile menu (pair programming)
binhussen/portfolio pull request #10
Opened 2022-07-19 09:25 UTC by binhussen

## Project 7: Mobile menu (pair programming)
In this section I have built for this milestone is:
- Added hamburger button, the mobile menu appears.
- Added the close (X) button, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears and a correct part of the page is displayed.

2022-07-19 09:39 UTC, omarsalem7 requested changes
Hi @binhussen, @DuaneDave  😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights
- Descriptive pull request ✔️
- Open/close functionality works correctly ✔️

## Required Changes ♻️

- [ ] _Check the comments under the review._
- [ ] Kindly update [linters.yml](https://github.com/microverseinc/linters-config/blob/master/html-css-js/.github/workflows/linters.yml) to check javascript linters also in GitHub workflows

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-19 09:39 UTC, omarsalem7 commented on styles.css
> +    height: 85%;
- [ ] It will be better to to `height: 100%`, so the mobile menu covers all layout.

2022-07-19 09:39 UTC, omarsalem7 commented on index.html
>              </a>
- [ ] Kindly add the correct `href` value to the corresponding section instead of `#`, so when I click on the mobile menu item, It will map to the specified section.

2022-07-19 10:58 UTC, binhussen commented on styles.css
> +    height: 85%;
- [ ] I don't think it covers all layouts in Figma design.
- [ ] kindly please check the Figma design https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471

2022-07-19 11:20 UTC, binhussen commented
## Project 7: Mobile menu (pair programming)
In this section I have built for this milestone is:
- update [linters.yml](https://github.com/microverseinc/linters-config/blob/master/html-css-js/.github/workflows/linters.yml) to check javascript linters also in GitHub workflows
- correct href value to the corresponding section instead of #, so when I click on the mobile menu item, It will map to the specified section.

2022-07-19 11:57 UTC, cynthiainga approved these changes
## STATUS APPROVED :green_circle: :green_circle:

Hi @team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- [ ] All linters are passing :heavy_check_mark: 
- [ ] Good commit history :heavy_check_mark: 
- [ ] Good implementation of all changes required :heavy_check_mark: 
- [ ] Descriptive pull request :heavy_check_mark: 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-19 11:58 UTC, merged

2022-10-22 14:40 UTC, binhussen commented on styles.css
> +    height: 85%;
Thanks, @omarsalem7 for your feedback, I forget to do so I will do it.

2022-10-22 14:40 UTC, binhussen commented on index.html
>              </a>
Thanks, @omarsalem7 for your feedback, I forget to do so I will do it.

2022-10-22 14:40 UTC, binhussen commented
Thank you @cynthiainga for your feedback and approval.